### ISSUE TITLE
Update link from IVT website

### ISSUE THREAD

**Issue by krlmlr** [mlfit/mlfit#56]
once we decided on the final location.

**Comment by asiripanich** [comment]
Our CRAN preparation is almost ready, if you decide to move the repo to the `mlfit` org account now might a good time to do that.

**Comment by krlmlr** [comment]
Moved, need to update all internal URLs. I'll create a pkgdown site that forwards to the new location.

**Comment by krlmlr** [comment]
Old website: https://krlmlr.github.io/mlfit/, should be rebuilt in a few.

**Comment by asiripanich** [comment]
@krlmlr can you update the repo link? Thanks.
