### ISSUE TITLE
The reference sample of Ye's example is missing an individual ID column

### ISSUE THREAD

**Issue by asiripanich** [mlfit/mlfit#57]
Here is the reference sample of Ye's example:
https://github.com/krlmlr/mlfit/blob/6f71e7151c87551b12110d1bf8d3ec1637189bfa/R/ml_problem.R#L32-L35

When creating a ml_problem, there is a individual id field (PNR) which doesn't exist in the reference sample.
https://github.com/krlmlr/mlfit/blob/6f71e7151c87551b12110d1bf8d3ec1637189bfa/R/ml_problem.R#L77-L81

**Comment by krlmlr** [comment]
But the example seems to run without error?

**Comment by asiripanich** [comment]
Yes, it runs without any error. But I'm fixing it so that `ml_replicate()` would work as expected. Or shouldn't we fix it?
