### ISSUE TITLE
Fix NEWS.md

### ISSUE THREAD

**Issue by maelle** [mlfit/mlfit#76]
@krlmlr I see pkgdown can't parse the oldest version https://mlfit.github.io/mlfit/news/index.html

It's because the title "v0.1 (2015-05-26)" is not one of the allowed syntaxes see https://pkgdown.r-lib.org/reference/build_news.html

**Comment by maelle** [comment]
Another issue in this changelog is that some version headers are h1 whereas others are h2 so in the pkgdown website you can see some versions are nested under "mlfit 0.3.7.9000"

**Comment by asiripanich** [comment]
Thank you @maelle for reporting the issue. I'm fixing it in #77.
