### ISSUE TITLE
Question regarding features available when `geo_hierarchy` is used

### ISSUE THREAD

**Issue by walkerke** [mlfit/mlfit#78]
Hi @krlmlr and @asiripanich,

First of all, many thanks for this package!  It is exactly what I've been looking for and I'm using it productively in several projects at the moment.  

I have a question about a couple errors / warnings I'm encountering in my work that I'm hoping you can clarify when you get the chance.  The specific source code I'm referencing is this section: https://github.com/mlfit/mlfit/blob/main/R/ml_problem.R#L178-L183.  

The `geo_hierarchy` feature is excellent.  However, when `geo_hierarchy` is used, there are a couple common use-cases that don't work:
- Single-level fitting problems (e.g. households only, or individuals only) can't be specified, specifically due to this section: https://github.com/mlfit/mlfit/blob/main/R/ml_problem.R#L168-L179.  This does work when a `geo_hierarchy` is not used.  
- The `prior_weights` argument can't be used when specifying a `geo_hierarchy` as well (https://github.com/mlfit/mlfit/blob/main/R/ml_problem.R#L181-L183).  

This leads me to a couple questions:
1. Are these limitations by design?
2. If they are not by design and just need some additional work to enable these features for region/zone fitting problems, would you be interested in a pull request to try to implement this?

If a minimal reproducible example would be helpful for discussion as well, let me know.  Thanks again!

**Comment by asiripanich** [comment]
Hi @walkerke,

I'm glad to hear that you're enjoying using the mlfit package. Your feedback reminds me that I need to finish the [get started](https://github.com/mlfit/mlfit/blob/6145763922bb5eb8ec2253eacd3e2a53da180405/vignettes/get-started.Rmd) vignette for mlfit, which also use your tidycensus package. 

I appreciate you bringing up the issues you've encountered, they are valid and should be addressed. I'll look into them early next week and make the necessary changes. However, if you get the chance to work on it before then, I'd be happy to review any pull requests you make. 

Thanks!

**Comment by walkerke** [comment]
Thanks so much for your work on this @asiripanich!
